### ISSUE TITLE
[유은나] Contact Menu

### ISSUE THREAD

**Issue by EunnaYoo** [EunnaYoo/DataSchool_Web#4]
Contact 메뉴도 동적으로 바꿔서 하위메뉴들 누르면 각각으로 가는 링크 걸어놨는데
뭐 때문인진 모르겠지만 페이지가 index.html에서만 눌렀을 때 동작하고 다른 페이지에서는
눌러도 동작하지 않네요 ㅠ ㅠ
코드 한 번 확인해주세요

**Comment by SEJSCloud** [comment]
intro.jsp 빼고 다른페이지에는 자바스크립트 함수 추가가 안되어있었습니다
각 페이지에 넣어서 해결했습니다~
