### ISSUE TITLE
[김종성] 2019.08.24 git 관련 문제

### ISSUE THREAD

**Issue by SEJSCloud** [EunnaYoo/DataSchool_Web#5]
git pull 실행시 오류발생
-> 새로운 로컬저장소 생성, git clone
-> 새로운 폴더 생성 후 로컬저장소 자료 복사해와서 환경셋팅 
-> 서버 오류 해결위해 이클립스 dataSchoolProject 폴더에 <property name="context-root" value="dataSchooolProject1"/> 추가해줌 (아침에 같이 설정해야될 부분일수도있음)
-> 해당 폴더에서 작업 후 작업 한 자료(dataSchooolProject폴더만) 복사해서 로컬저장소에 붙여넣기 및 덮어씌우기 
-> 소스트리에서 commit후 원격저장소 feature/ExamMenu에 push -> 오류가 나면서 완료됨
     (상세메시지는 밑에)이 뜨면서 push됨 
-> 원격저장소에는 오늘 작업한 자료 push 되어있음 
-> 뭐가 문제인지 검색해봤는데 해당 오류 글귀를 부분 부분 검색해보면 로컬저장소 브랜치가 원격저장소 브랜치에 tracking을 멈추게 하는 방법설명이나옴 
-> 뭔소린지 모르겠음..ㅠㅠ 
-> 깃은나님 도와주세요.. 
-> 혹시 모르니 월요일 아침에 git pull 먼저 하지 않는게 좋아보입니다

(오류 메시지) - git -c diff.mnemonicprefix=false -c core.quotepath=false --no-optional-locks config --file C:\webbackup\.git\config --unset branch.develop.merge
오류가 나면서 완료됨.

**Comment by EunnaYoo** [comment]
에러 발생했는데 push가 원격에 됐다는 말이니 push에러라는 거죠 ?

**Comment by EunnaYoo** [comment]
> git pull 실행시 오류발생
> -> 새로운 로컬저장소 생성, git clone
> -> 새로운 폴더 생성 후 로컬저장소 자료 복사해와서 환경셋팅
> -> 서버 오류 해결위해 이클립스 dataSchoolProject 폴더에 추가해줌 (아침에 같이 설정해야될 부분일수도있음)
> -> 해당 폴더에서 작업 후 작업 한 자료(dataSchooolProject폴더만) 복사해서 로컬저장소에 붙여넣기 및 덮어씌우기
> -> 소스트리에서 commit후 원격저장소 feature/ExamMenu에 push -> 오류가 나면서 완료됨
> (상세메시지는 밑에)이 뜨면서 push됨
> -> 원격저장소에는 오늘 작업한 자료 push 되어있음
> -> 뭐가 문제인지 검색해봤는데 해당 오류 글귀를 부분 부분 검색해보면 로컬저장소 브랜치가 원격저장소 브랜치에 tracking을 멈추게 하는 방법설명이나옴
> -> 뭔소린지 모르겠음..ㅠㅠ
> -> 깃은나님 도와주세요..
> -> 혹시 모르니 월요일 아침에 git pull 먼저 하지 않는게 좋아보입니다
> 
> (오류 메시지) - git -c diff.mnemonicprefix=false -c core.quotepath=false --no-optional-locks config --file C:\webbackup.git\config --unset branch.develop.merge
> 오류가 나면서 완료됨.

에러 발생했는데 push가 원격에 됐다는 말이니 push에러라는 거죠 ?

**Comment by SEJSCloud** [comment]
넵 다시 푸쉬하면 already up to date 문구 뜨는데 오류메시지는 그대로 나옵니다

**Comment by EunnaYoo** [comment]
끝
