### ISSUE TITLE
[김종성] 18:00 ~ To-Do list

### ISSUE THREAD

**Issue by EunnaYoo** [EunnaYoo/DataSchool_Web#8]
* 기출문제 메뉴
    - 첫 번째 문제 하단에 정답확인 버튼을 누르면 버튼 밑에 정답과 해설 글자 보이게 하기
    ( 1시간 30분만 도전 하다 안되면 때려치우고 집가거나 알고리즘이나 풀기 )

**Comment by SEJSCloud** [comment]
![정답캡쳐1](https://user-images.githubusercontent.com/52445900/63683252-d5a92f00-c834-11e9-9340-0f47116f7264.PNG)

클릭 후 캡쳐


![정답캡쳐2](https://user-images.githubusercontent.com/52445900/63683241-cde98a80-c834-11e9-9e4c-7dd40b9ca166.PNG)

클릭 전 캡쳐

이렇게 만들라는거 맞나요?

**Comment by EunnaYoo** [comment]
오 이것도 좋은 방법인거같아요 !! 굿 !
이제 프로젝트 손대지 말구 알고리즘 풀면서 머리 식히세요 ㅎ ㅎ

**Comment by SEJSCloud** [comment]
넹 푹쉬다 오세요~
