### ISSUE TITLE
[김종성] 09:00 ~ To-Do List

### ISSUE THREAD

**Issue by EunnaYoo** [EunnaYoo/DataSchool_Web#9]
종성씨 제가 몸이 좀 안좋아서 오늘 학원에 조금 늦게 도착할거 같아요 그래도 오후가 되기 전엔 도착하도록할테니 적어 놓은 것만 하고 계시면 될 거 같아요 ! 죄송합니다 ㅠ
- 기출문제 풀이 나머지 문제 ( 2 ~ 5 ) 1 번 문제랑 똑같이 만들기
- 남은건 오후에 저랑 같이
- 저것만 다 하시면 알고리즘 하고 계세요 ! 저희 시간 안촉박하니까 !

**Comment by SEJSCloud** [comment]
알겠습니당 푹 쉬고 말짱해져서 돌아오세요
